import { User, Event, Article, ImpactStats } from './types';

// Sample Users
export const sampleUsers: User[] = [
  {
    id: 1,
    name: 'Alice Green',
    email: 'alice.green@example.com',
    role: 'user',
    points: 15,
    registeredEventIds: [1, 3, 4, 5],
    proofSubmittedEventIds: [],
    submittedReports: [],
  },
  {
    id: 2,
    name: 'Bob Carter',
    email: 'bob.carter@example.com',
    role: 'admin',
    points: 8,
    registeredEventIds: [6],
    proofSubmittedEventIds: [],
    submittedReports: [],
  },
  {
    id: 3,
    name: 'Charlie Davis',
    email: 'charlie.davis@example.com',
    role: 'user',
    points: 5,
    registeredEventIds: [1, 4],
    proofSubmittedEventIds: [],
    submittedReports: [],
  },
];

// Sample Events
export const sampleEvents: Event[] = [
  {
    id: 1,
    title: 'Lakeside Park Clean-Up',
    description: 'Join us for a community clean-up event at Lakeside Park. We will be collecting litter, removing invasive plants, and helping to restore the natural beauty of the area. All supplies will be provided. Please wear sturdy shoes and bring a water bottle.',
    category: 'Community Clean-Up',
    date: '2024-08-15',
    time: '09:00 AM - 12:00 PM',
    location: 'Lakeside Park, Springfield',
    image: 'https://picsum.photos/seed/event1/400/300',
    organizerId: 2,
    volunteersNeeded: 50,
    volunteers: [1, 3],
    pointsValue: 3,
  },
  {
    id: 2,
    title: 'Oakwood Forest Reforestation',
    description: 'Help us plant 500 native saplings in Oakwood Forest to support local wildlife and improve air quality. No prior experience needed! We will provide training and tools. A great event for families.',
    category: 'Tree Planting',
    date: '2024-09-05',
    time: '10:00 AM - 02:00 PM',
    location: 'Oakwood Forest Trailhead',
    image: 'https://picsum.photos/seed/event2/400/300',
    organizerId: 2,
    volunteersNeeded: 75,
    volunteers: [],
    pointsValue: 3,
  },
  {
    id: 3,
    title: 'City Center E-Waste Drive',
    description: 'Got old electronics? Bring them to our e-waste recycling drive! We are collecting old computers, phones, batteries, and other electronic devices for safe and responsible disposal.',
    category: 'Recycling Program',
    date: '2024-09-20',
    time: '11:00 AM - 03:00 PM',
    location: 'City Hall Parking Lot',
    image: 'https://picsum.photos/seed/event3/400/300',
    organizerId: 2,
    volunteersNeeded: 20,
    volunteers: [1],
    pointsValue: 2,
  },
   {
    id: 4,
    title: 'Riverbank Restoration Project',
    description: 'A past event. Join us to help stabilize the riverbank by planting native grasses and removing debris. This is crucial work to prevent erosion and protect water quality. Lunch will be provided for all volunteers.',
    category: 'Conservation',
    date: '2024-06-22',
    time: '09:30 AM - 01:30 PM',
    location: 'Green River, Mile Marker 5',
    image: 'https://picsum.photos/seed/event4/400/300',
    organizerId: 2,
    volunteersNeeded: 40,
    volunteers: [1, 3],
    pointsValue: 3,
  },
  {
    id: 5,
    title: 'Annual Beach Sweep',
    description: 'A past event. Help keep our beaches clean and safe for wildlife! We will be combing the shoreline for plastic and other harmful waste.',
    category: 'Community Clean-Up',
    date: '2024-07-10',
    time: '08:00 AM - 11:00 AM',
    location: 'Sunset Beach Pier',
    image: 'https://picsum.photos/seed/event5/400/300',
    organizerId: 2,
    volunteersNeeded: 100,
    volunteers: [1],
    pointsValue: 2,
  },
   {
    id: 6,
    title: 'Downtown Recycling Program Kickoff',
    description: 'A past event created by admin Bob Carter. We are launching a new recycling program for downtown businesses and need volunteers to help distribute materials and educate owners.',
    category: 'Recycling Program',
    date: '2024-05-18',
    time: '10:00 AM - 1:00 PM',
    location: 'Main Street Plaza',
    image: 'https://picsum.photos/seed/event6/400/300',
    organizerId: 2,
    volunteersNeeded: 25,
    volunteers: [2],
    pointsValue: 2,
  }
];

// Sample Articles
export const sampleArticles: Article[] = [
  {
    id: 1,
    title: '10 Simple Ways to Reduce Your Carbon Footprint',
    summary: 'Living a more sustainable lifestyle doesn\'t have to be complicated. Here are 10 easy changes you can make today to reduce your environmental impact.',
    content: '1. Reduce, Reuse, Recycle: The three R\'s are a cornerstone of sustainable living.\n2. Conserve Water: Simple habits like turning off the tap while brushing your teeth can save gallons of water.\n3. Choose Sustainable Transportation: Walk, bike, or use public transit whenever possible.\n4. Switch to LED Lightbulbs: They use significantly less energy and last much longer than traditional bulbs.\n5. Eat Less Meat: Reducing meat consumption, especially red meat, can lower your carbon footprint.\n6. Compost Your Food Scraps: Composting reduces methane emissions from landfills.\n7. Go Paperless: Opt for digital bills and statements.\n8. Unplug Electronics: Many devices use energy even when they\'re turned off.\n9. Shop Locally: Supporting local farmers and businesses reduces transportation emissions.\n10. Plant a Tree: Trees absorb carbon dioxide and provide vital habitats for wildlife.',
    author: 'Jane Doe',
    date: '2024-07-20',
    image: 'https://picsum.photos/seed/article1/400/300',
  },
  {
    id: 2,
    title: 'The Importance of Pollinators and How to Help Them',
    summary: 'Bees, butterflies, and other pollinators are essential for our ecosystems and food supply. Learn why they are in danger and what you can do to help.',
    content: 'Pollinators are responsible for one out of every three bites of food we eat. Unfortunately, their populations are declining due to habitat loss, pesticide use, and climate change. You can help by planting a pollinator-friendly garden with native flowers, avoiding pesticides, and providing a water source. Even a small container garden on a balcony can make a difference!',
    author: 'John Smith',
    date: '2024-07-15',
    image: 'https://picsum.photos/seed/article2/400/300',
  },
  {
    id: 3,
    title: 'Understanding the Dangers of Single-Use Plastics',
    summary: 'Single-use plastics are a major source of pollution, harming wildlife and ecosystems. Discover the impact of these materials and find sustainable alternatives.',
    content: 'From plastic bags to water bottles, single-use plastics are everywhere. They take hundreds of years to break down and often end up in our oceans, where they can be ingested by marine animals. You can combat this problem by carrying a reusable water bottle, using cloth shopping bags, and choosing products with minimal packaging.',
    author: 'EcoAction Team',
    date: '2024-07-10',
    image: 'https://picsum.photos/seed/article3/400/300',
  },
];

// Sample Impact Stats
export const sampleImpactStats: ImpactStats = {
  eventsCreated: 25,
  totalVolunteers: 1240,
  treesPlanted: 3500,
  wasteCollectedKg: 850,
};